/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';
import '@stencil/state-tunnel';

import {
  MatchResults,
} from '@stencil/router';

declare global {

  namespace StencilComponents {
    interface AppHome {

    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppMachineStatus {
      'machine': any;
    }
  }

  interface HTMLAppMachineStatusElement extends StencilComponents.AppMachineStatus, HTMLStencilElement {}

  var HTMLAppMachineStatusElement: {
    prototype: HTMLAppMachineStatusElement;
    new (): HTMLAppMachineStatusElement;
  };
  interface HTMLElementTagNameMap {
    'app-machine-status': HTMLAppMachineStatusElement;
  }
  interface ElementTagNameMap {
    'app-machine-status': HTMLAppMachineStatusElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-machine-status': JSXElements.AppMachineStatusAttributes;
    }
  }
  namespace JSXElements {
    export interface AppMachineStatusAttributes extends HTMLAttributes {
      'machine'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppProfile {
      'match': MatchResults;
    }
  }

  interface HTMLAppProfileElement extends StencilComponents.AppProfile, HTMLStencilElement {}

  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  interface ElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-profile': JSXElements.AppProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface AppProfileAttributes extends HTMLAttributes {
      'match'?: MatchResults;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppRoot {

    }
  }

  interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-root': JSXElements.AppRootAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRootAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface DemoButton {

    }
  }

  interface HTMLDemoButtonElement extends StencilComponents.DemoButton, HTMLStencilElement {}

  var HTMLDemoButtonElement: {
    prototype: HTMLDemoButtonElement;
    new (): HTMLDemoButtonElement;
  };
  interface HTMLElementTagNameMap {
    'demo-button': HTMLDemoButtonElement;
  }
  interface ElementTagNameMap {
    'demo-button': HTMLDemoButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'demo-button': JSXElements.DemoButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface DemoButtonAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StButton {

    }
  }

  interface HTMLStButtonElement extends StencilComponents.StButton, HTMLStencilElement {}

  var HTMLStButtonElement: {
    prototype: HTMLStButtonElement;
    new (): HTMLStButtonElement;
  };
  interface HTMLElementTagNameMap {
    'st-button': HTMLStButtonElement;
  }
  interface ElementTagNameMap {
    'st-button': HTMLStButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'st-button': JSXElements.StButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface StButtonAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
